# Generated by Django 3.2.6 on 2021-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=50)),
                ('uname', models.CharField(default='', max_length=50)),
                ('cemail', models.CharField(default='', max_length=50)),
                ('cmob', models.CharField(default='', max_length=12)),
                ('cadd', models.CharField(default='', max_length=100)),
                ('ccity', models.CharField(default='', max_length=50)),
                ('cweb', models.CharField(default='', max_length=50)),
                ('cdesc', models.CharField(default='', max_length=50)),
                ('cimg', models.ImageField(default='', upload_to='collage/images')),
                ('cstatus', models.CharField(default='no', max_length=50)),
            ],
        ),
    ]
