# Generated by Django 3.2.6 on 2021-08-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collage',
            old_name='ccity',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cdesc',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cadd',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cemail',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cname',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cweb',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cimg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cmob',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='cstatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='collage',
            old_name='uname',
            new_name='web',
        ),
    ]
