# Generated by Django 3.2.6 on 2021-08-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_auto_20210812_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='web',
        ),
    ]
